# Generated by Django 3.2.10 on 2022-01-05 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dhun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
