# Generated by Django 4.0.1 on 2022-02-11 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhun', '0002_alter_album_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'aac', 'wav', 'mp4'])]),
        ),
    ]
