# Generated by Django 4.0.1 on 2022-02-17 11:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhun', '0003_alter_album_image_alter_song_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[9,7,8,6]\\d{9}$', 'invalid phone number')])),
                ('photo', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif'])])),
                ('bio', models.TextField(max_length=1000)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
